# Every test file has one or more tests...
test_name: Test GET simple

stages:
  - name: Make sure we have the right ID

    request:
      url: http://127.0.0.1:5000/books/1
      method: GET

    response:
      status_code: 200
      body:
        id: 1
        title : Les lutteurs immobiles
        year : 1985

---

test_name : Test UPDATE

stages:
  - name: test update title & year of book id = 1 
    request:
      url: http://127.0.0.1:5000/books/1
      method: PUT
      json:
        id: 1
        title : Les lutteurs non immobiles
        year : 1986
    
    response:
      status_code: 200

  - name: check book with id=1 really modified
    request:
      url: http://127.0.0.1:5000/books/1
      method: GET

    response:
      status_code: 200
      body:
        id: 1
        title : Les lutteurs non immobiles
        year : 1986

---        

test_name : Test CREATION

stages:
  - name: test creation of new book
    request:
      url: http://127.0.0.1:5000/books/
      method: POST
      json:
        title : Le rire du lance flamme
        year : 1984
        fff : hello
    
    response:
      status_code: 201
      body:
        id: 4
        
  
  - name: check book with id=4 really created
    request:
      url: http://127.0.0.1:5000/books/4
      method: GET

    response:
      status_code: 200
      body:
        id: 4
        title : Le rire du lance flamme
        year : 1984

---        

test_name : Test DELETION

stages:
  - name: test deletion of book
    request:
      url: http://127.0.0.1:5000/books/4
      method: DELETE
      
    response:
      status_code: 200
      
  - name: test book id 4 no more exists
    request:
      url: http://127.0.0.1:5000/books/4
      method: GET
      
    response:
      status_code: 404
